swagger: '2.0'
info:
  description: >
    This is a sample swagger file to explore some of the Synology Web APIs.
    [Generate your own swagger file](https://github.com/mikespub/synology)


    If you want to try this out on your own Synology, this requires adding
    a rest.php file in the base directory of your Web Station to act as a
    gateway to the actual Synology Web APIs.


    Except for SYNO.API.Info query, most API calls assume that you have
    logged in first via SYNO.API.Auth, and received a session id (sid).
    You will need to update the default value of the _sid parameter below
    in your swagger file so that all API calls can use the right value.


    There are many versions of the swagger file available, one using short
    urls with query parameters, and the other specifying the complete path
    including the 4 standard parameters for each API method. Any special
    additional parameters needed for a particular API method are not taken
    into account here (except for login).

  version: 1.0.0
  title: Synology Web API Explorer
  contact:
    url: 'https://github.com/mikespub/synology/issues'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: diskstation
basePath: /rest.php
schemes:
  - http
securityDefinitions:
  query_sid:
    type: apiKey
    name: _sid
    in: query
consumes:
  - application/json
  - text/plain
produces:
  - application/json
  - text/plain
definitions:
  NormalResponse:
    type: object
    properties:
      success:
        type: boolean
        description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
      data:
        type: object
        description: The data object contains all the response information described in each method.
      error:
        type: object
        properties:
          code:
            type: integer
            description: An integer number error code will be returned when a request fails.
          errors:
            type: array
            items:
              type: object
paths:
  /SYNO.API.Info/v1/query:
    get:
      tags:
        - API
      summary: Return query for SYNO.API.Info
      operationId: API_Info_query
      parameters:
        - in: query
          name: query
          description: Requested API information
          required: true
          type: string
          default: all
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/login:
    get:
      tags:
        - API
      summary: Return login for SYNO.API.Auth
      operationId: API_Auth_login
      parameters:
        - in: query
          name: account
          description: Username
          required: false
          type: string
          default: username
        - in: query
          name: passwd
          description: Password
          required: false
          type: string
          default: passwd
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
        - in: query
          name: format
          description: Format (cookie or sid)
          required: false
          type: string
          default: sid
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/logout:
    get:
      tags:
        - API
      summary: Return logout for SYNO.API.Auth
      operationId: API_Auth_logout
      parameters:
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.BTSearch/v1/start:
    get:
      tags:
        - DownloadStation.BTSearch
      summary: Return start for SYNO.DownloadStation.BTSearch
      operationId: BTSearch_start
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.BTSearch/v1/list:
    get:
      tags:
        - DownloadStation.BTSearch
      summary: Return list for SYNO.DownloadStation.BTSearch
      operationId: BTSearch_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.BTSearch/v1/getCategory:
    get:
      tags:
        - DownloadStation.BTSearch
      summary: Return getCategory for SYNO.DownloadStation.BTSearch
      operationId: BTSearch_getCategory
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.BTSearch/v1/clean:
    get:
      tags:
        - DownloadStation.BTSearch
      summary: Return clean for SYNO.DownloadStation.BTSearch
      operationId: BTSearch_clean
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.BTSearch/v1/getModule:
    get:
      tags:
        - DownloadStation.BTSearch
      summary: Return getModule for SYNO.DownloadStation.BTSearch
      operationId: BTSearch_getModule
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Info/v2/getinfo:
    get:
      tags:
        - DownloadStation.Info
      summary: Return getinfo for SYNO.DownloadStation.Info
      operationId: Info_getinfo
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Info/v2/getconfig:
    get:
      tags:
        - DownloadStation.Info
      summary: Return getconfig for SYNO.DownloadStation.Info
      operationId: Info_getconfig
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Info/v2/setserverconfig:
    get:
      tags:
        - DownloadStation.Info
      summary: Return setserverconfig for SYNO.DownloadStation.Info
      operationId: Info_setserverconfig
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.RSS.Feed/v1/list:
    get:
      tags:
        - DownloadStation.RSS
      summary: Return list for SYNO.DownloadStation.RSS.Feed
      operationId: RSS_Feed_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.RSS.Site/v1/list:
    get:
      tags:
        - DownloadStation.RSS
      summary: Return list for SYNO.DownloadStation.RSS.Site
      operationId: RSS_Site_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.RSS.Site/v1/refresh:
    get:
      tags:
        - DownloadStation.RSS
      summary: Return refresh for SYNO.DownloadStation.RSS.Site
      operationId: RSS_Site_refresh
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Schedule/v1/getconfig:
    get:
      tags:
        - DownloadStation.Schedule
      summary: Return getconfig for SYNO.DownloadStation.Schedule
      operationId: Schedule_getconfig
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Schedule/v1/setconfig:
    get:
      tags:
        - DownloadStation.Schedule
      summary: Return setconfig for SYNO.DownloadStation.Schedule
      operationId: Schedule_setconfig
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Statistic/v1/getinfo:
    get:
      tags:
        - DownloadStation.Statistic
      summary: Return getinfo for SYNO.DownloadStation.Statistic
      operationId: Statistic_getinfo
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Task/v3/list:
    get:
      tags:
        - DownloadStation.Task
      summary: Return list for SYNO.DownloadStation.Task
      operationId: Task_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Task/v3/getinfo:
    get:
      tags:
        - DownloadStation.Task
      summary: Return getinfo for SYNO.DownloadStation.Task
      operationId: Task_getinfo
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Task/v3/create:
    get:
      tags:
        - DownloadStation.Task
      summary: Return create for SYNO.DownloadStation.Task
      operationId: Task_create
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Task/v3/delete:
    get:
      tags:
        - DownloadStation.Task
      summary: Return delete for SYNO.DownloadStation.Task
      operationId: Task_delete
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Task/v3/resume:
    get:
      tags:
        - DownloadStation.Task
      summary: Return resume for SYNO.DownloadStation.Task
      operationId: Task_resume
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Task/v3/pause:
    get:
      tags:
        - DownloadStation.Task
      summary: Return pause for SYNO.DownloadStation.Task
      operationId: Task_pause
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.DownloadStation.Task/v3/edit:
    get:
      tags:
        - DownloadStation.Task
      summary: Return edit for SYNO.DownloadStation.Task
      operationId: Task_edit
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
