swagger: '2.0'
info:
  description: >
    This is a sample swagger file to explore some of the Synology Web APIs.
    [Generate your own swagger file](https://github.com/mikespub/synology)


    If you want to try this out on your own Synology, this requires adding
    a rest.php file in the base directory of your Web Station to act as a
    gateway to the actual Synology Web APIs.


    Except for SYNO.API.Info query, most API calls assume that you have
    logged in first via SYNO.API.Auth, and received a session id (sid).
    You will need to update the default value of the _sid parameter below
    in your swagger file so that all API calls can use the right value.


    There are many versions of the swagger file available, one using short
    urls with query parameters, and the other specifying the complete path
    including the 4 standard parameters for each API method. Any special
    additional parameters needed for a particular API method are not taken
    into account here (except for login).

  version: 1.0.0
  title: Synology Web API Explorer
  contact:
    url: 'https://github.com/mikespub/synology/issues'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: diskstation
basePath: /rest.php
schemes:
  - http
securityDefinitions:
  query_sid:
    type: apiKey
    name: _sid
    in: query
consumes:
  - application/json
  - text/plain
produces:
  - application/json
  - text/plain
definitions:
  NormalResponse:
    type: object
    properties:
      success:
        type: boolean
        description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
      data:
        type: object
        description: The data object contains all the response information described in each method.
      error:
        type: object
        properties:
          code:
            type: integer
            description: An integer number error code will be returned when a request fails.
          errors:
            type: array
            items:
              type: object
paths:
  /SYNO.API.Info/v1/query:
    get:
      tags:
        - API
      summary: Return query for SYNO.API.Info
      operationId: API_Info_query
      parameters:
        - in: query
          name: query
          description: Requested API information
          required: true
          type: string
          default: all
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/login:
    get:
      tags:
        - API
      summary: Return login for SYNO.API.Auth
      operationId: API_Auth_login
      parameters:
        - in: query
          name: account
          description: Username
          required: false
          type: string
          default: username
        - in: query
          name: passwd
          description: Password
          required: false
          type: string
          default: passwd
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
        - in: query
          name: format
          description: Format (cookie or sid)
          required: false
          type: string
          default: sid
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/logout:
    get:
      tags:
        - API
      summary: Return logout for SYNO.API.Auth
      operationId: API_Auth_logout
      parameters:
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Client/v1/list:
    get:
      tags:
        - OAUTH.Client
      summary: Return list for SYNO.OAUTH.Client
      operationId: Client_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Client/v1/get:
    get:
      tags:
        - OAUTH.Client
      summary: Return get for SYNO.OAUTH.Client
      operationId: Client_get
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Client/v1/add:
    get:
      tags:
        - OAUTH.Client
      summary: Return add for SYNO.OAUTH.Client
      operationId: Client_add
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Client/v1/enable:
    get:
      tags:
        - OAUTH.Client
      summary: Return enable for SYNO.OAUTH.Client
      operationId: Client_enable
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Client/v1/disable:
    get:
      tags:
        - OAUTH.Client
      summary: Return disable for SYNO.OAUTH.Client
      operationId: Client_disable
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Client/v1/del:
    get:
      tags:
        - OAUTH.Client
      summary: Return del for SYNO.OAUTH.Client
      operationId: Client_del
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Common/v1/get:
    get:
      tags:
        - OAUTH.Common
      summary: Return get for SYNO.OAUTH.Common
      operationId: Common_get
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Common/v1/set:
    get:
      tags:
        - OAUTH.Common
      summary: Return set for SYNO.OAUTH.Common
      operationId: Common_set
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Log/v1/list:
    get:
      tags:
        - OAUTH.Log
      summary: Return list for SYNO.OAUTH.Log
      operationId: Log_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Log/v1/del:
    get:
      tags:
        - OAUTH.Log
      summary: Return del for SYNO.OAUTH.Log
      operationId: Log_del
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Log/v1/add:
    get:
      tags:
        - OAUTH.Log
      summary: Return add for SYNO.OAUTH.Log
      operationId: Log_add
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Log/v1/export:
    get:
      tags:
        - OAUTH.Log
      summary: Return export for SYNO.OAUTH.Log
      operationId: Log_export
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Token/v1/list:
    get:
      tags:
        - OAUTH.Token
      summary: Return list for SYNO.OAUTH.Token
      operationId: Token_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Token/v1/revoke:
    get:
      tags:
        - OAUTH.Token
      summary: Return revoke for SYNO.OAUTH.Token
      operationId: Token_revoke
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.OAUTH.Token/v1/verify:
    get:
      tags:
        - OAUTH.Token
      summary: Return verify for SYNO.OAUTH.Token
      operationId: Token_verify
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
