swagger: '2.0'
info:
  description: >
    This is a sample swagger file to explore some of the Synology Web APIs.
    [Generate your own swagger file](https://github.com/mikespub/synology)


    If you want to try this out on your own Synology, this requires adding
    a rest.php file in the base directory of your Web Station to act as a
    gateway to the actual Synology Web APIs.


    Except for SYNO.API.Info query, most API calls assume that you have
    logged in first via SYNO.API.Auth, and received a session id (sid).
    You will need to update the default value of the _sid parameter below
    in your swagger file so that all API calls can use the right value.


    There are many versions of the swagger file available, one using short
    urls with query parameters, and the other specifying the complete path
    including the 4 standard parameters for each API method. Any special
    additional parameters needed for a particular API method are not taken
    into account here (except for login).

  version: 1.0.0
  title: Synology Web API Explorer
  contact:
    url: 'https://github.com/mikespub/synology/issues'
  license:
    name: MIT
    url: 'https://opensource.org/licenses/MIT'
host: diskstation
basePath: /rest.php
schemes:
  - https
  - http
securityDefinitions:
  query_sid:
    type: apiKey
    name: _sid
    in: query
consumes:
  - application/json
  - text/plain
produces:
  - application/json
  - text/plain
definitions:
  NormalResponse:
    type: object
    properties:
      success:
        type: boolean
        description: '"true" when the request finishes successfully, "false" when the request fails with an error code.'
      data:
        type: object
        description: The data object contains all the response information described in each method.
      error:
        type: object
        properties:
          code:
            type: integer
            description: An integer number error code will be returned when a request fails.
          errors:
            type: array
            items:
              type: object
paths:
  /SYNO.API.Info/v1/query:
    get:
      tags:
        - API
      summary: Return query for SYNO.API.Info
      operationId: API_Info_query
      parameters:
        - in: query
          name: query
          description: Requested API information
          required: true
          type: string
          default: all
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/login:
    get:
      tags:
        - API
      summary: Return login for SYNO.API.Auth
      operationId: API_Auth_login
      parameters:
        - in: query
          name: account
          description: Username
          required: false
          type: string
          default: username
        - in: query
          name: passwd
          description: Password
          required: false
          type: string
          default: passwd
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
        - in: query
          name: format
          description: Format (cookie or sid)
          required: false
          type: string
          default: sid
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
  /SYNO.API.Auth/v4/logout:
    get:
      tags:
        - API
      summary: Return logout for SYNO.API.Auth
      operationId: API_Auth_logout
      parameters:
        - in: query
          name: session
          description: Session Name
          required: true
          type: string
          default: DownloadStation
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.APIRunner/v1/upload:
    get:
      tags:
        - SAS.APIRunner
      summary: Return upload for SYNO.SAS.APIRunner
      operationId: APIRunner_upload
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.APIRunner/v1/adapter:
    get:
      tags:
        - SAS.APIRunner
      summary: Return adapter for SYNO.SAS.APIRunner
      operationId: APIRunner_adapter
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.APIRunner/v1/exec:
    get:
      tags:
        - SAS.APIRunner
      summary: Return exec for SYNO.SAS.APIRunner
      operationId: APIRunner_exec
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.APIRunner.Chatbot/v1/receive:
    get:
      tags:
        - SAS.APIRunner
      summary: Return receive for SYNO.SAS.APIRunner.Chatbot
      operationId: APIRunner_Chatbot_receive
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Encryption/v1/status:
    get:
      tags:
        - SAS.Encryption
      summary: Return status for SYNO.SAS.Encryption
      operationId: Encryption_status
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Encryption/v1/exchange:
    get:
      tags:
        - SAS.Encryption
      summary: Return exchange for SYNO.SAS.Encryption
      operationId: Encryption_exchange
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Group/v1/get:
    get:
      tags:
        - SAS.Group
      summary: Return get for SYNO.SAS.Group
      operationId: Group_get
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Group/v1/set:
    get:
      tags:
        - SAS.Group
      summary: Return set for SYNO.SAS.Group
      operationId: Group_set
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Group.Members/v1/add:
    get:
      tags:
        - SAS.Group
      summary: Return add for SYNO.SAS.Group.Members
      operationId: Group_Members_add
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Group.Members/v1/remove:
    get:
      tags:
        - SAS.Group
      summary: Return remove for SYNO.SAS.Group.Members
      operationId: Group_Members_remove
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Group.Members/v1/list:
    get:
      tags:
        - SAS.Group
      summary: Return list for SYNO.SAS.Group.Members
      operationId: Group_Members_list
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Guest/v1/notify:
    get:
      tags:
        - SAS.Guest
      summary: Return notify for SYNO.SAS.Guest
      operationId: Guest_notify
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Guest/v1/authorize:
    get:
      tags:
        - SAS.Guest
      summary: Return authorize for SYNO.SAS.Guest
      operationId: Guest_authorize
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Guest/v1/cancel:
    get:
      tags:
        - SAS.Guest
      summary: Return cancel for SYNO.SAS.Guest
      operationId: Guest_cancel
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Guest/v1/stat:
    get:
      tags:
        - SAS.Guest
      summary: Return stat for SYNO.SAS.Guest
      operationId: Guest_stat
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Guest/v1/invite:
    get:
      tags:
        - SAS.Guest
      summary: Return invite for SYNO.SAS.Guest
      operationId: Guest_invite
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Guest/v1/set:
    get:
      tags:
        - SAS.Guest
      summary: Return set for SYNO.SAS.Guest
      operationId: Guest_set
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
  /SYNO.SAS.Guest/v1/get:
    get:
      tags:
        - SAS.Guest
      summary: Return get for SYNO.SAS.Guest
      operationId: Guest_get
      responses:
        '200':
          description: Normal Response
          schema:
            $ref: '#/definitions/NormalResponse'
        default:
          description: Abnormal Response
          schema:
            type: object
      security:
        - query_sid: []
